from django.contrib import admin
from models import *
# Register your models here.
admin.site.register(Customer)
admin.site.register(Profile)
admin.site.register(Franchise)
admin.site.register(Category)
admin.site.register(Product)
admin.site.register(Package)
admin.site.register(PackageMask)
admin.site.register(Service)
admin.site.register(ServiceMask)
admin.site.register(Stock)
admin.site.register(StockTransfer)
admin.site.register(StockReturn)
admin.site.register(SalesReport)
admin.site.register(SalesReportBase)
admin.site.register(AuditReport)
admin.site.register(Treatment)
admin.site.register(TreatmentMaster)
admin.site.register(Enquiry)
admin.site.register(Note)
admin.site.register(TimestampDB)
admin.site.register(Discount)
admin.site.register(LoginHistory)
admin.site.register(LoginTimestamps)
admin.site.register(HOProduct)
admin.site.register(SKUList)
admin.site.register(PendingTreatment)
admin.site.register(PendingPrescription)
admin.site.register(Receipt)
admin.site.register(IDGenerator)