# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Client')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('pending_amount', models.FloatField()),
                ('number', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('issue_date', models.DateField()),
                ('method', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Profile')),
            ],
        ),
    ]
