# Generated by Django 2.0.6 on 2018-06-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20180613_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinginvoice',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendinginvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='Customer.Customer'),
        ),
    ]
