# Generated by Django 2.0.6 on 2018-06-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20180613_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('pending', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='Customer.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='pendinginvoice',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PendingInvoice',
        ),
    ]
