# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
            preserve_default=False,
        ),
    ]
