# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loginhistory_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTimestamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='loginhistory',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='timestamps',
        ),
        migrations.AddField(
            model_name='logintimestamps',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LoginHistory'),
        ),
    ]
