# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180325_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('amount', models.FloatField(max_length=20)),
                ('cashier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('franchise', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Franchise')),
            ],
        ),
        migrations.AlterModelManagers(
            name='loginhistory',
            managers=[
            ],
        ),
    ]
