# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180401_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='details',
            field=models.CharField(max_length=100),
        ),
    ]
