# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180404_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 4, 16, 34, 30, 666305, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
