# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='bill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesReportBase'),
        ),
    ]
