# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20180620_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='NONE', max_length=10),
            preserve_default=False,
        ),
    ]
