# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.FileField(upload_to='posters'),
        ),
    ]
